### ISSUE TITLE
Feature request: docker-compose file

### ISSUE THREAD

**Issue by magick93** [comicrelief/docker-php7-drupal#1]
Hi

It would be great if this could also have a docker-compose file so that it can both spin up drupal, but also the database, and have them connected.

**Comment by Saphyel** [comment]
@magick93 you can use one like this:
```
version: '2'
services:
  web:
    image: comicrelief/php7-drupal
    ports:
      - 8080:80
    links:
      - mysql
      - rabbitmq
      - solr
    volumes:
      - my/path:/var/www/html
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
solr:
    image: solr:6.3-alpine
    ports:
      - 8984:8983
    volumes:
      - my/path/modules/contrib/search_api_solr/solr-conf/6.x:/drupal/conf
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - campaign
      - /drupal
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    hostname: drupal-rabbit
    environment:
      RABBITMQ_HIPE_COMPILE: 1
```
